services:
  seerr-syncerr:
    image: ghcr.io/bymem/seerr-syncerr:latest
    container_name: seerr-syncerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
      - PORT=8070
    volumes:
      - ./config:/config
    ports:
      - "8070:8070"
    restart: unless-stopped
