services:
  seerr-syncerr:
    build: .
    container_name: seerr-syncerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
      - PORT=8089
    volumes:
      - ./config:/config
    ports:
      - "8089:8089"
    restart: unless-stopped
